export { default as Header } from './header/Header'
export { default as About } from './about/About'
export { default as Projects } from './projects/Projects'
export { default as Contact } from './contact/Contact'
export { default as Footer } from './footer/Footer'
export { default as Animations } from './animations/Animations'
